# configure the version
set(CMAKE_WIZARD_PATCH 0)
set(CMAKE_WIZARD_MINOR 0)
set(CMAKE_WIZARD_MAJOR 0)
set(CMAKE_WIZARD_VERSION "${CMAKE_WIZARD_MAJOR}.${CMAKE_WIZARD_MINOR}.${CMAKE_WIZARD_PATCH}")

add_definitions(-DCMAKE_WIZARD_VERSION="${CMAKE_WIZARD_VERSION}")